export const FETCH_TASK = "FETCH_TASK";
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_FAILED = "FETCH_TASK_FAILED";

export const FILTER_TASK = "FILTER_TASK";
export const FILTER_TASK_SUCCESS = "FILTER_TASK_SUCCESS";

export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERR = "ADD_TASK_ERR";

export const EDITTING_TASK = "EDITTING_TASK";

export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_ERR = "UPDATE_TASK_ERR";

export const DEL_TASK = "DEL_TASK";
export const DEL_TASK_SUCCESS = "DEL_TASK_SUCCESS";
export const DEL_TASK_ERR = "DEL_TASK_ERR";
